# ----
# Site

title: CRUX Docs
description: API documentation for CRUXconnect
url: https://api.cruxconnect.com
google_analytics_key:
permalink: pretty
baseurl: ""

collections:
  documentation:
    visibility: all
    title: Documentation
    position: 1
  login:
    visibility: public
    title: Login
    position: 2
    type: api
  organization:
    visibility: public
    title: Organization
    position: 3
    type: api
  accounting:
    visibility: public
    title: Accounting
    position: 4
    type: api
  product_retailer:
    visibility: public
    title: Product for Retailers
    position: 5
    type: api
  product_supplier:
    visibility: public
    title: Product for Supplier
    position: 5
    type: api
  ordering:
    visibility: public
    title: Ordering
    position: 6
    type: api
  export:
    visibility: public
    title: Export
    position: 7
    type: api
  tools:
    visibility: internal
    title: Operations Tools
    position: 8
    type: api

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
