# ----
# Site

title: CRUX Docs
description: API documentation for CRUXconnect
url: https://api.cruxconnect.com
google_analytics_key:
permalink: pretty
baseurl: ""

collections:
  documentation:
    visibility: all
    title: Documentation
    position: 1.0
  file_specs_documentation:
    visibility: file-specs
    title: Item File Specifications
    position: 1.1
    type: fs
  sku_specs_documentation:
    visibility: file-specs
    title: SKU File Specifications
    position: 1.2
    type: fs
  organization:
    visibility: public
    title: Organization
    position: 2
    type: api
  accounting:
    visibility: public
    title: Accounting
    position: 3
    type: api
  product:
    visibility: all
    title: Product
    position: 4
    type: api
  product_retailer:
    visibility: all
    title: Product for Retailers
    position: 4.1
    type: api
  product_supplier:
    visibility: public
    title: Product for Supplier
    position: 4.2
    type: api
  ordering:
    visibility: public
    title: Ordering
    position: 5
    type: api
  ordering_retailer:
    visibility: public
    title: Ordering for Retailer
    position: 5.1
    type: api
  ordering_supplier:
    visibility: public
    title: Ordering for Supplier
    position: 5.2
    type: api
  discovery:
    visibility: public
    title: Discovery
    position: 6
    type: api
  discovery_retailer:
    visibility: public
    title: Discovery Retailer
    position: 6.1
    type: api
  files:
    visibility: public
    title: Files
    position: 7
    type: api
  tools:
    visibility: internal
    title: Operations Tools
    position: 10
    type: api

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - common/links

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
