# ----
# Site

title: Thanos Docs
description: API documentation for project codenamed thanos
url: https://example.com
google_analytics_key:
permalink: pretty
baseurl: /thanos-api-docs

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: APIs
    position: 2
    type: api
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
  - patch
